@startuml
'https://plantuml.com/sequence-diagram

autonumber

Principal -> TransaccionBancaria: realizarTransferencia()
TransaccionBancaria --> ManejadorPersistecniaLogImpl: buscarCuenta()
ManejadorPersistecniaLogImpl --> ManejadorPersistecniaImpl: buscarCuenta()

ManejadorPersistecniaLogImpl <-- ManejadorPersistecniaImpl
TransaccionBancaria <-- ManejadorPersistecniaLogImpl
Principal <-- TransaccionBancaria
@enduml